# overrides for dev environment
services:
  back:
    build:
      target: dev
    volumes:
      - ./back/app:/code/app
  
  front:
    build:
      target: dev
    volumes:
      - ./front/public:/code/public
      - ./front/src:/code/src
    environment:
      - NODE_ENV=development