services:
  back:
    build: 
      context: ./back
    ports:
      - 3005:80
  
  front:
    build:
      context: ./front
    ports:
      - 3000:3000
  
  db:
    image: mariadb:latest
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mariadb_data: