# overrides for dev environment
services:
  back:
    build:
      target: dev
    volumes:
      - ./back/app:/code/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=testdb
    depends_on:
      db:
        condition: service_healthy
  
  front:
    build:
      target: dev
    volumes:
      - ./front/public:/code/public
      - ./front/src:/code/src
    environment:
      NODE_ENV: development

  db:
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 1m
